Use FUS in AppCenterDistributeV3
annakocheshkova/azure-pipelines-tasks pull request #1
Opened 2020-06-23 09:14 UTC by annakocheshkova

**Task name**: AppCenterDistributeV3

**Description**: Switch to using FUS for uploading the file.

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

Note: unit tests are in a separate PR. No need to bump task version yet.

2020-06-24 14:12 UTC, MatkovIvan requested changes

2020-06-24 14:12 UTC, MatkovIvan commented on Tasks/AppCenterDistributeV3/appcenterdistribute.ts
> +function beginReleaseUpload(apiServer: string, apiVersion: string, appSlug: string, token: string, userAgent: string, buildVersion: string): Q.Promise<any> {
Can we avoid `any` here?

2020-06-24 14:12 UTC, MatkovIvan commented on Tasks/AppCenterDistributeV3/appcenterdistribute.ts
> +            if (!response.package_asset_id || (response.statusCode && response.statusCode !== 200)) {
All 2xx are valid codes

2020-06-24 14:12 UTC, MatkovIvan commented on Tasks/AppCenterDistributeV3/appcenterdistribute.ts
> +        "internal-request-source": "VSTS"
It's still VSTS? (not AzDO)

2020-06-26 15:40 UTC, MatkovIvan approved these changes
Only nitpick. The code looks good in general, but I didn't test it personally

2020-06-26 15:40 UTC, MatkovIvan commented on Tasks/AppCenterDistributeV3/appcenterdistribute.ts
> +        let uploadInfo: any = await beginReleaseUpload(effectiveApiServer, effectiveApiVersion, appSlug, apiToken, userAgent, buildVersion);
I guess it's not "any"

2020-06-29 08:04 UTC, Jamminroot approved these changes

2020-06-29 10:11 UTC, merged